name: Cargo build

on:
  pull_request:
    branches: [ master ]

jobs:
  build_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test -- --include-ignored
      - run: cargo test --examples
      - run: cargo doc --no-deps
      - run: cargo install cargo-deadlinks
      - run: cargo deadlinks
      - run: rustup component add clippy
      - run: bin/clippy-pedantic.sh
      - run: cargo bench --no-run --profile dev
      - run: cargo clean
      - run: rustup default nightly
      - run: rustup component add llvm-tools-preview
      - run: curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -
      - run: PATH=$PATH:$(pwd) bin/coverage-report.sh
      - run: bash <(curl -s https://codecov.io/bash) -f lcov.info
  build_32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cross
      - run: cross test --target i686-unknown-linux-gnu
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.66.0
      - run: cargo install cargo-criterion
      - run: cargo criterion --bench cri_rand -- next_u64
      - run: cargo criterion --bench cri_rand -- next_u128